#!/bin/bash

# Load all ChenPi11 scripts.
dir="$HOME/.local/share/chenpi11"
while IFS= read -r -d '' file; do
    source "$file"
done < <(find "$dir" -maxdepth 1 \( -name '*.sh' -o -name '*.bash' \) -print0 | sort -z)

